
package com.hand.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldServer", targetNamespace = "http://hand.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorld", targetNamespace = "http://hand.com/", className = "com.hand.client.GetHelloWorld")
    @ResponseWrapper(localName = "getHelloWorldResponse", targetNamespace = "http://hand.com/", className = "com.hand.client.GetHelloWorldResponse")
    @Action(input = "http://hand.com/HelloWorldServer/getHelloWorldRequest", output = "http://hand.com/HelloWorldServer/getHelloWorldResponse")
    public String getHelloWorld();

}
